### ISSUE TITLE
Merge some pxb icons with material icons

### ISSUE THREAD

**Issue by huayunh** [pxblue/icons#100]
#### Describe the desired behavior

Certain icon categories might be grouped together for better search-ability 

Examples: 
* Building & Places
* Devices, Lighting -> Hardware
  * Note that there are two categories right now, Device (from material design) and Devices (a pxb category). But I think the pxb category goes better with the "hardware" category
* General - break those into "action" and "communication"
  * Account settings & lock reset - action
  * Internet connection - communication
* Industrial 
  * "Building" and "Factory" can be reassigned to "places"
* Platform & Platforms
* Status
  * Most of these can be regrouped into "industrial" 
  * Some can go to "Social", "Hardware"
  * This category also contains some duplicates of material icons
* Transportation, Vehicles, Maps
  * At least the first two categories can go together

#### Is this request related to a current issue?

pxblue/doc-it#304 is another issue about icon categories

#### Additional Context

This issue may be transported to the icons repo, but the metadata is only used on docit, so...

**Comment by joebochill** [comment]
Let's have a bigger discussion about this with Studio Blue (Eric) to decide which icons we want to go into which categories. In general, we should be able to maximize our use of the existing Material categories, and only create our own for PX Blue icons that really don't fit into the existing categories (like the Platforms).

**Comment by jeffvg** [comment]
moved to PXBLUE-1916
