### ISSUE TITLE
React Progress Icon readme is lost

### ISSUE THREAD

**Issue by huayunh** [pxblue/icons#113]
#### Describe the bug

There is no React Progress Icon readme in the file tree. There is an Angular one.

#### What is the expected behavior?

Both should present, and the Readme links in https://github.com/pxblue/icons/tree/dev/progress#install-and-use should work.

#### What are the steps to reproduce?
N/A

**Comment by joebochill** [comment]
The README does exist. It's nested one folder down in the /icons folder inside of /react folder. We just need to update the link in that Readme. :)
