### ISSUE TITLE
BLUI icon does not appear as it should

### ISSUE THREAD

**Issue by neerujahL** [pxblue/icons#173]
**Describe the bug**

PX Blue icon named Motor Outline displays differently when used.

**What is the expected behaviour?**

Motor outline should display as: 
![image](https://user-images.githubusercontent.com/95443565/144493303-833e442a-e97f-4178-a155-33e3d8b4016d.png)
Instead it appears like so: 
![image](https://user-images.githubusercontent.com/95443565/144493460-45c4d69a-59e1-4c0f-b52b-76f103c1e459.png)

**What are the steps to reproduce?**

1.  Visit C:\dev\git\angular\web-components\src\styles\_icons.scss 
2.  Replace .wc-icon-induction-motor from @include wc-cyme-icon($cyme-font-induction-motor, 1.50em) to  @include wc-blui-icon($blui-font-motor_outline) 
3. To use icon on any html file: 
    <i class="wc-icon-induction-motor"></i>

**What is your environment?**
Framework - Angular
Browser - Edge
Operating System - Windows

**Comment by huayunh** [comment]
This sounds like a build issue; the `motor_outline` and `network_switch` are close to each other in `iconfont/BrightlayerUIIcons.css`, but I am not an ng-expert... @emclaug2, wants to have a look at this?

**Comment by emclaug2** [comment]
Hey @neerujahL , what package & version of icons are you using?

**Comment by neerujahL** [comment]
Found a bug in the version 1.7.1 that was fixed in 1.8.0 for the motor outline icon. It displays accordingly.

**Comment by emclaug2** [comment]
This is fixed in 1.8.0; thanks @neerujahL !
