### ISSUE TITLE
Support for the "charging bolt" in Battery Progress icons

### ISSUE THREAD

**Issue by ericatha** [pxblue/icons#24]
#### Bug or feature request?
Support for the "charging bolt" in Battery Progress icons

#### What is the expected behavior?
A battery icon should show its remaining charge level, but should also show when it is charging vs not. The icon should have a charging bolt in the center while charging.

#### What is the current behavior?
No option for a battery that is currently charging

#### What are the steps to reproduce?
1.

#### What is your environment?

 Framework
- [ ] Angular
- [ ] React

 Browser
- [ ] Internet Explorer
- [ ] Safari
- [ ] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [ ] Windows
- [ ] Other

**Comment by shivanipitta** [comment]
merged on PR #38 
updates will be available on the following versions
Angular: 1.1.2
react: 1.0.7
