### ISSUE TITLE
Add Query or Fragment to URL to allow direct linking to icons

### ISSUE THREAD

**Issue by ericatha** [pxblue/icons#26]
#### Bug or feature request?
Adding something to the url so that we can link to specific icons

e.g. pxblue.etn.com/style/iconography/#flow or pxblue.etn.com/style/iconography/?icon=water

#### What is the expected behavior?
Some way to link directly to an icon or perhaps search as well if we use query

**Comment by joebochill** [comment]
Closing this as it's a request for documentation site, which is tracked in JIRA
