### ISSUE TITLE
Progress icons for React Native

### ISSUE THREAD

**Issue by joebochill** [pxblue/icons#48]
#### Describe the desired behavior
It would be nice to have progress icons that work in React Native

#### Describe the current behavior
Currently, React Native throws errors on invalid components (rect, etc.) when using the React progress icons.

#### Is this request related to a current issue?
No

#### Additional Context
We should be able to make SVGs work using react-native-svg library, just need to build dedicated components for react-native.

**Comment by jeffvg** [comment]
Does this work with React Native svg transformer...

**Comment by jeffvg** [comment]
moved to PXBLUE-1919
