### ISSUE TITLE
Eaton Logo with Tagline

### ISSUE THREAD

**Issue by joebochill** [pxblue/icons#49]
#### Describe the desired behavior
We need to add Eaton logos to the PX Blue icon set. These should include the plain Eaton logo and the one with the "Powering Business Worldwide" tagline.

#### Describe the current behavior
Basic icon is in the hidden section right now. The one with tagline does not exist.

#### Is this request related to a current issue?
This is related to requests coming from product teams about where to find the logos.

**Comment by huayunh** [comment]
quite strange to put the tagline version in our repo... makes sense for the basic icon

**Comment by joebochill** [comment]
Why does the small one make sense but not the big one? The big one is the official Eaton logo. The one without the tag line is only supposed to be used when the tag line one is too small to read. Both of these are by popular demand from adopters.

**Comment by huayunh** [comment]
Just a feeling that it is less "icon" -- does the tagline one also has to be 24*24 view box?

**Comment by joebochill** [comment]
If we want it to work well with the automatic creator utility for MUI Icons, yes. It might be a little goofy, but the EATON one will already be a little goofy since it's a rectangle too.
