### ISSUE TITLE
Remove bounding box thing from the generated svg/ folder

### ISSUE THREAD

**Issue by huayunh** [pxblue/icons#68]
#### Describe the desired behavior

the invisible 24*24 bounding box is not necessary -- see my comments in the following PR: 

>> Be sure to include a 24x24px rectangle with no stroke and no fill to serve as the bounding box.

> I personally did not follow this last time when I was making changes in this repo. (1) we had to manually remove the bounding box when we import them into Figma; (2) the same functionality can be achieved by checking "use artboards" option when the saving/file naming dialog box pop up (so not part of the export options window, which appears in the next screen)
> _Originally posted by @huayunh in https://github.com/pxblue/icons/pull/66#discussion_r461677173_

#### Describe the current behavior

> I checked all of the icons: 109/139 have the bounding box. If we're going to change it, we should make them all the same. We can do that in a separate issue. 
--- Joe

**Comment by huayunh** [comment]
I noticed that in `icons-mui/scripts/mui-icon-builder/builder.js`, there's these code -- 

![image](https://user-images.githubusercontent.com/8997218/90555606-9f5f7080-e165-11ea-98e4-06ab831a22a2.png)

It further justifies removing the bounding box thing 😛

**Comment by joebochill** [comment]
Did you check to see if this causes an issue with the clickable area of the icon when it is used as a button. Vertical 3-dot menu can be very hard to click if it only has an 8px wide hit box.

**Comment by huayunh** [comment]
I experimented in icons mui, and the hitbox is not affected. I tried with some small icons and it looks fine.

**Comment by joebochill** [comment]
Okay, can we also try them in the React Native Showcase? I know we've had clickable area issues in RN before and just want to be safe.

I would just render one big icon in the middle of the screen (like the 3-dot icon) and see if clicking in the Viewbox but not on the path still triggers the event. If that works, i'll be satisfied.

**Comment by huayunh** [comment]
![ezgif-2-4b12836aa1e8](https://user-images.githubusercontent.com/8997218/93009158-288e7b00-f54b-11ea-98bf-2bbdf6f8862f.gif)

**Comment by joebochill** [comment]
The Header creates a 40x40 clickable area for the icon buttons. Using an icon directly:

![Animated GIF-downsized_large](https://user-images.githubusercontent.com/29152776/93074985-27e10c00-f653-11ea-8c31-ec4b4a22be2e.gif)

**Comment by huayunh** [comment]
OK. I will close this then. 

(Reason for taking that bounding box out was I thought it wasn't necessary, as commented in the description)

**Comment by joebochill** [comment]
As mentioned in the PR, the use case here is pretty uncommon. We can reopen this and close it through that PR.

May also be worth looking at my comment on https://github.com/pxblue/react-native-component-library/issues/69 which discusses a potential change to how we do icons in RN anyway, which could bring back that clickable area without having it defined in the SVG.

**Comment by joebochill** [comment]
We may want to add some information to the Readme about using these in React Native. There is a specific situation where the clickable area of the icon may be limited to just the icon shape (not the whole viewbox) unless you wrap in in a Touchable component.
