### ISSUE TITLE
Outlined progress icons are hiding the percentages

### ISSUE THREAD

**Issue by huayunh** [pxblue/icons#69]
#### Describe the bug
Our outlined versions of the progress icons are 

#### What is the expected behavior?

The percentage calculation should take into account for the border width

#### Screenshots or links to minimum reproduction example
from docit, if you make everything outlined:
![image](https://user-images.githubusercontent.com/8997218/89819684-d5737380-db19-11ea-9621-45b25b312474.png)

Notice that for the battery icons and the heart icons, column 1 and column 9 are supposed to be 10% and 90% respectively, yet it gets displayed as 0% and 100% because of the outline. 

#### Environment

React progress icon

**Comment by huayunh** [comment]
Weird, when I added those ups icons in https://github.com/pxblue/icons/pull/70, the whole thing seems to render differently

**Comment by huayunh** [comment]
![image](https://user-images.githubusercontent.com/8997218/90142936-fc64bc00-dd4a-11ea-95c9-72600a6ab41b.png)
This is driving me mad... the #70 got merged, docit with `"@pxblue/react-progress-icons": "^2.0.0"` got updated, and this problem recurred.

**Comment by joebochill** [comment]
For react, this was an issue in version 2.0.0 only. It worked correctly in 1.0.7:

It looks like when we converted to typescript we accidentally overwrote the props with the default props in the constructor where we set the start position of the fill:
![image](https://user-images.githubusercontent.com/29152776/90241702-93884d00-ddf9-11ea-8104-41952f4d82f0.png)

This got fixed when it was converted to functional components, so it actually works as expected in dev right now:
![image](https://user-images.githubusercontent.com/29152776/90241827-d0544400-ddf9-11ea-9200-9ccad2917dcd.png)


Is this an issue with the angular progress icons as well? If not, I think we can close this issue.

**Comment by huayunh** [comment]
![image](https://user-images.githubusercontent.com/8997218/90248322-7ad26400-de06-11ea-80ad-251e17f33fd5.png)

docit dev is not really working? 

And it works fine in Angular showcase, yes

**Comment by joebochill** [comment]
Doc-it dev is using version 2.0.0 (latest published version)...if you build the dev branch of progress icons and hot-load it into doc-it, it's working fine...we just need to publish a new version of the progress icons and it will be resolved.

**Comment by huayunh** [comment]
I see

**Comment by joebochill** [comment]
I think when I said 'working in dev' it was confugin...i meant dev of the progress icons, not dev of doc-it 👍
