### ISSUE TITLE
Split this Repo

### ISSUE THREAD

**Issue by emclaug2** [pxblue/icons#82]
#### Describe the desired behavior
This repo should be split into smaller repositories. 

#### Describe the current behavior
We have 2 demo projects, 2 progress icon libraries in this repo.  
The scripts used to generate resources are getting confusing and verbose.  
It's time to split this repo up.  

Make a react-progress-icons repo.
Make an angular-progress-icons repo.
Make another repo for symbols resources.
Make another for shared icon resources.

#### Is this request related to a current issue?
No

**Comment by jeffvg** [comment]
moved to PXBLUE-1917
